# Spring props
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  file:
    name: log/${SPRING_PROFILES_ACTIVE}.log
  level:
    org.hibernate.SQL: DEBUG

server:
  port: ${API_PORT}
  error:
    include-stacktrace: on_trace_param # never in production

firebase:
  service-account: ${FIREBASE_SERVICE_ACCOUNT}
