name: ci

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  ci:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: jacocoTestReport

      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@4.8.6
        if: always()
        with:
          reports: 'build/reports/jacoco/test/jacocoTestReport.xml'
          targetdir: 'build/reports/ReportGenerator'
          reporttypes: 'TextSummary'
          verbosity: 'Warning'

      - name: write PR Comment
        uses: actions/github-script@v3
        if: always()
        with:
          script: |
            const fs = require('fs');
            let text = fs.readFileSync("build/reports/ReportGenerator/Summary.txt", 'utf-8');
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: text
            })
